name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-basic-build:
    runs-on: ubuntu-latest
    name: Test basic Docker build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test build with automatic tags
        uses: ./
        with:
          image: test/myapp
          base_tag: test-${{ github.run_number }}
          context: ./test
          dockerfile: ./test/Dockerfile
          push: false
          load: true

      - name: Verify image was loaded
        run: |
          docker images | grep -E "test/myapp.*test-${{ github.run_number }}"
          docker images | grep -E "test/myapp.*sha-"
          docker run --rm test/myapp:test-${{ github.run_number }} echo "Container runs successfully"

  test-manual-tags:
    runs-on: ubuntu-latest
    name: Test with manual tags
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test build with manual tags
        uses: ./
        with:
          tags: |
            test/app:v1.0.0
            test/app:latest
          context: ./test
          dockerfile: ./test/Dockerfile
          push: false
          load: true

      - name: Verify images
        run: |
          docker images | grep -E "test/app.*v1.0.0"
          docker images | grep -E "test/app.*latest"
          docker run --rm test/app:v1.0.0 echo "Version tag works"
          docker run --rm test/app:latest echo "Latest tag works"

  test-buildx-config:
    runs-on: ubuntu-latest
    name: Test custom buildx configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test with custom buildx settings
        uses: ./
        with:
          tags: test/buildx:custom
          context: ./test
          dockerfile: ./test/Dockerfile
          buildx_driver: docker-container
          buildx_name: custom-builder
          buildx_driver_opts: |
            network=bridge
          buildx_buildkitd_flags: --debug
          buildx_install: true
          push: false
          load: true

      - name: Verify build and buildx configuration
        run: |
          # Check that our custom builder was created
          docker buildx ls | grep -E "custom-builder.*docker-container"

          # Verify the image was built
          docker images | grep -E "test/buildx.*custom"

          # Test that the image runs
          docker run --rm test/buildx:custom echo "Custom buildx config works"

  test-multi-platform:
    runs-on: ubuntu-latest
    name: Test multi-platform build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test multi-platform build (push disabled)
        uses: ./
        with:
          tags: test/multiarch:test
          context: ./test
          dockerfile: ./test/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          # Note: load is not set to true because multi-platform builds can't be loaded

      - name: Inspect manifest
        run: docker buildx imagetools inspect test/multiarch:test || echo "Expected - image not pushed"

  test-build-args:
    runs-on: ubuntu-latest
    name: Test with build arguments
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test build with args
        uses: ./
        with:
          tags: test/args:test
          context: ./test
          dockerfile: ./test/Dockerfile.args
          build_args: |
            TEST_ARG=hello
            VERSION=${{ github.sha }}
          push: false
          load: true

      - name: Verify build args
        run: |
          docker run --rm test/args:test sh -c 'echo $TEST_ARG'